  version: '2'

services:
  postgres:
    restart: always
    env_file:
      - env
    image: postgres
    container_name: praktomat_db
    expose:
      - "5432"
  praktomat:
    build: .
    container_name: django_praktomat
    restart: always
    env_file:
      - env
    # command: python2 .praktomat/bin/praktomat runserver 0.0.0.0:8000
    volumes:
      - /Users/oliverwork/git/praktomat/docker-data:/praktomat
    expose:
      - "8000"
    links:
      - postgres
    depends_on:
      - postgres